services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mmuser_password
      POSTGRES_DB: mattermost
      LANG: C.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mmuser -d mattermost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mattermost:
    image: mattermost/mattermost-team-edition:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mmuser:mmuser_password@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
      MM_SERVICESETTINGS_SITEURL: https://${CODESPACE_NAME}-8065.team-edition.app.github.dev
      MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
      MM_SERVICESETTINGS_ENABLEDEVELOPER: "true"
    ports:
      - "8065:8065"
      - "8443:8443"
    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_config:/mattermost/config
      - mattermost_logs:/mattermost/logs
      - mattermost_plugins:/mattermost/plugins
      - mattermost_client_plugins:/mattermost/client/plugins

volumes:
  postgres_data:
  mattermost_data:
  mattermost_config:
  mattermost_logs:
  mattermost_plugins:
  mattermost_client_plugins: